FROM jenkins/jenkins:lts-jdk17

USER root

# install tools
RUN apt-get update && apt-get install -y curl ca-certificates gnupg \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs git \
  && node -v && npm -v \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
